//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ChartStudio.rc
//
#define IDC_MYICON                      2
#define IDD_CHARTSTUDIO_DIALOG          102
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_CHARTSTUDIO                 107
#define IDI_SMALL                       108
#define IDC_CHARTSTUDIO                 109
#define ID_FILE_NEW                     110
#define ID_FILE_OPEN                    111
#define ID_FILE_SAVE                    112
#define ID_FILE_SAVEAS                  113
#define ID_FILE_EXIT                    114
#define ID_CHARTS_BOUNDVALUES           117
#define ID_CHARTS_MARKLEFT              118
#define ID_CHARTS_MARKRIGHT             119
#define ID_CHARTS_MARKTOP               120
#define ID_CHARTS_MARKBOTTOM            121
#define ID_VIEW_CHARTSETTINGS           122
#define ID_VIEW_UISETTINGS              123
#define ID_VIEW_RESETVIEW               124
#define ID_VIEW_SMOOTHIMAGES            125
#define ID_OBJ_ADDLINEAR                126
#define ID_OBJ_ADDCLAMP                 127
#define IDR_MAINFRAME                   128
#define ID_OBJ_ADDTREND                 128
#define IDB_TOOLBAR                     129
#define ID_OBJ_ADDPOLY                  129
#define IDB_ADD                         130
#define ID_OBJ_ADDTABLE                 130
#define IDB_ADDLINE                     131
#define ID_OBJ_ADDSCRIPT                131
#define IDB_ADDPOINTS                   132
#define ID_OBJ_UP                       132
#define ID_OBJ_DOWN                     133
#define IDB_CANCEL                      134
#define ID_OBJ_DELETE                   134
#define IDB_CLAMP                       135
#define ID_INPUT_ADD                    135
#define IDB_ADDCLAMP                    136
#define ID_INPUT_DELETE                 136
#define IDB_DELETE                      137
#define ID_INPUT_UP                     137
#define IDB_DOWN                        138
#define ID_INPUT_DOWN                   138
#define IDB_EXPORT                      139
#define ID_CONSTANT_UP                  139
#define IDB_HIDE                        140
#define ID_CONSTANT_DOWN                140
#define IDB_LINEAR                      141
#define ID_CONSTANT_ADD                 141
#define IDB_ADDLINEAR                   142
#define ID_CONSTANT_DELETE              142
#define IDB_POLY                        143
#define ID_IMAGE_ADD                    143
#define IDB_ADDPOLY                     144
#define ID_IMAGE_DELETE                 144
#define IDB_REMOVEPOINTS                145
#define ID_LINES_NEWLINE                145
#define IDB_ROTATE                      146
#define ID_LINES_ADDPOINTS              146
#define IDB_SCRIPT                      147
#define ID_LINES_REMOVEPOINT            147
#define IDB_ADDSCRIPT                   148
#define ID_LINES_DELETE                 148
#define IDB_SHOW                        149
#define ID_TABLE_ADDENTRY               149
#define IDB_TABLE                       150
#define ID_TABLE_DELETEENTRY            150
#define IDB_ADDTABLE                    151
#define IDC_CHARTNAME                   151
#define IDC_EXPORTRESULT                152
#define IDB_TREND                       153
#define IDC_ERRORTEXT                   153
#define IDB_ADDTREND                    154
#define IDC_INPUTAXISISX                154
#define IDB_UP                          155
#define IDC_INPUTAXISISY                155
#define IDC_INPUT1LIST                  156
#define IDR_INPUTMENU                   156
#define IDC_INPUT2LIST                  157
#define IDC_INPUT3LIST                  158
#define IDC_INPUT1TEXT                  159
#define IDC_INPUT2TEXT                  160
#define IDC_INPUT3TEXT                  161
#define IDC_SELLINEWIDTH                162
#define IDC_SELNODESIZE                 163
#define IDC_UNSELLINEWIDTH              164
#define IDC_UNSELNODESIZE               165
#define IDC_INACTIVELINEWIDTH           166
#define IDC_INACTIVENODESIZE            167
#define IDC_SELLINECOLOR                168
#define IDC_SELNODECOLOR                169
#define IDC_UNSELLINECOLOR              170
#define IDC_UNSELNODECOLOR              171
#define IDC_INACTIVELINECOLOR           172
#define IDC_INACTIVENODECOLOR           173
#define IDC_RIGHTBOUND                  174
#define IDC_LEFTBOUND                   175
#define IDC_TOPBOUND                    176
#define IDC_BOTTOMBOUND                 177
#define IDC_NAME                        178
#define IDC_VALUE                       179
#define IDC_COMPILEERROR                180
#define IDC_NAMESTATIC                  181
#define IDC_REFERENCE                   182
#define IDC_RUN_SHOWALLLOBJECTS         183
#define IDC_RUN_SHOWEXPORTSONLY         184
#define IDC_RUNCHARTS                   185
#define IDC_RUN_SHOWALLOBJECTS          186
#define IDD_BOUNDS                      187
#define IDD_CHARTSETTINGS               188
#define IDD_EDITIMAGE                   189
#define IDD_EDITINPUT                   190
#define IDD_EDITSCRIPT                  191
#define IDD_EDITTABLEITEM               192
#define IDD_EDITVARIABLE                193
#define IDD_PROJECTSETTINGS             194
#define IDD_RUNCHARTS                   195
#define IDR_CHARTBOXMENU                196
#define IDR_TABLEBOXMENU                205
#define ID_TABLE_EDITITEM               206
#define IDR_IMAGESBOXMENU               207
#define ID_IMAGE_EDITNAME               208
#define ID_IMAGE_CENTERVIEW             209
#define IDR_LINESBOXMENU                210
#define ID_LINES_COPY                   211
#define IDR_CONSTANTMENU                211
#define ID_LINES_PASTE                  212
#define ID_LINES_EDIT                   213
#define ID_INPUT_EDIT                   214
#define ID_CONSTANT_EDIT                215
#define ID_OBJ_EDIT                     32772
#define ID_OBJ_CENTERVIEW               32773
#define ID_OBJ_COPYBOUNDS               32774
#define ID_OBJ_PASTEBOUNDS              32775
#define ID_OBJ_TOGGLEEXPORT             32776
#define ID_OBJ_INPUTAXISISX             32777
#define ID_OBJ_INPUTAXISISY             32778
#define ID_DATA_TESTCHAR                32779
#define ID_DATA_RUNCHARTS               32780
#define ID_EDITINPUT                    32781
#define ID__DFG                         32782
#define ID__DELETEINPUT                 32783
#define ID_FILE_NEW32784                32784
#define ID_FILE_OPEN32785               32785
#define ID_FILE_SAVE32786               32786
#define ID_FILE_SAVEAS32787             32787
#define ID_VIEW_RESETVIEW32788          32788
#define ID_VIEW_SETTINGS                32789
#define ID_EXPORT_EXPORTHTML            32790
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        157
#define _APS_NEXT_COMMAND_VALUE         32791
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           216
#endif
#endif
